In [1]:
import torch
from torch import nn

## 最大汇聚层和平均汇聚层

In [2]:
def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    Y = torch.zeros((X.shape[0]-p_h+1, X.shape[1]-p_w+1))
    for i in range(X.shape[0]-p_h+1):
        for j in range(X.shape[1]-p_w+1):
            match mode:
                case 'max':
                    Y[i, j] = torch.max(X[i:i+p_h, j:j+p_w])
                case 'avg':
                    Y[i, j] = torch.mean(X[i:i+p_h, j:j+p_w])
                case _:
                    raise ValueError(f'Invalid pooling mode: {mode}')
    return Y
            

In [3]:
X = torch.arange(.0, 9, 1.0).reshape(3, 3)
pool2d(X, (2, 2))

tensor([[4., 5.],
        [7., 8.]])

## 填充和步幅

In [4]:
X = torch.arange(16, dtype=torch.float32).reshape(1, 1, 4, 4)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [5]:
pool2d = nn.MaxPool2d(3) ## 默认步长为(3,3)
pool2d(X)

tensor([[[[10.]]]])

In [6]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

## 多个通道

In [7]:
X = torch.cat((X, X+1), 1)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [8]:
"""example
T = torch.arange(16).reshape(2, 8)
stackT = torch.stack([T, T], dim=0)
catT = torch.cat([T, T], dim=0)
stackT, catT
"""
"""output
(tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7],
          [ 8,  9, 10, 11, 12, 13, 14, 15]],
 
         [[ 0,  1,  2,  3,  4,  5,  6,  7],
          [ 8,  9, 10, 11, 12, 13, 14, 15]]]),
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
         [ 8,  9, 10, 11, 12, 13, 14, 15],
         [ 0,  1,  2,  3,  4,  5,  6,  7],
         [ 8,  9, 10, 11, 12, 13, 14, 15]]))
"""

'output\n(tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7],\n          [ 8,  9, 10, 11, 12, 13, 14, 15]],\n \n         [[ 0,  1,  2,  3,  4,  5,  6,  7],\n          [ 8,  9, 10, 11, 12, 13, 14, 15]]]),\n tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],\n         [ 8,  9, 10, 11, 12, 13, 14, 15],\n         [ 0,  1,  2,  3,  4,  5,  6,  7],\n         [ 8,  9, 10, 11, 12, 13, 14, 15]]))\n'

In [9]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2) ## 每个通道单独运算
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])

## Exercises

1. 尝试将平均汇聚层作为卷积层的特殊情况实现

2. 尝试将最大汇聚层作为卷积层的特殊情况实现

3. 假设汇聚层的输入大小为$(c,h,w)$，则汇聚窗口的形状为$(p_h, p_W)$，填充为$(p_h, p_w)$，步幅为$(s_h, s_w)$。这个汇聚层的计算成本是多少

4. 为什么最大汇聚层和平均汇聚层的工作方式不同？

5. 我们是否需要最小汇聚层？可以用已知函数替换它吗？

6. 除了平均汇聚层和最大汇聚层，是否有其它函数可以考虑（提示：回想一下softmax）？为什么它不流行？