In [2]:
import torch
from torch import nn
import torch.nn.functional as F

## 不带参数的层

In [3]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super(CenteredLayer, self).__init__()
    def forward(self, x):
        return x - x.mean()

In [4]:
layer = CenteredLayer()
layer(torch.FloatTensor([[1,2,3,4,5,6], [7,8,9,10,11,12]]))

tensor([[-5.5000, -4.5000, -3.5000, -2.5000, -1.5000, -0.5000],
        [ 0.5000,  1.5000,  2.5000,  3.5000,  4.5000,  5.5000]])

In [5]:
net = nn.Sequential(
    nn.Linear(8, 128),
    CenteredLayer()
)

In [6]:
y = net(torch.rand(4, 8))
y.mean()

tensor(-3.7253e-09, grad_fn=<MeanBackward0>)

## 带参数的层

In [7]:
class MyLinear(nn.Module):
    def __init__(self, in_units, out_units):
        super(MyLinear, self).__init__()
        self.weight = nn.Parameter(torch.randn(in_units, out_units))
        self.bias = nn.Parameter(torch.randn(out_units,))
    def forward(self, x):
        return F.relu(torch.matmul(x, self.weight.data)+self.bias.data)

In [8]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 1.7259, -1.8263, -0.3034],
        [ 0.0422,  0.4794,  0.0155],
        [ 0.6059, -0.0780, -0.8093],
        [-0.4897,  0.1320,  1.1047],
        [ 0.2228, -0.3905,  1.2890]], requires_grad=True)

In [21]:
net = nn.Sequential(
    MyLinear(64, 8),
    MyLinear(8, 1)
)
net(torch.rand(2, 64))

tensor([[0.0000],
        [1.6325]])

## Exercises

1. 设计一个接受输入并计算张量降维的层，它返回$y_k = \sum_{i, j}W_{ijk}{x_i}{x_j}$

2. 设计一个返回输入数据的傅立叶系数前半部分的层