In [1]:
import torch
from torch import nn
from torch.nn import functional as F

## 加载和保存张量

In [3]:
x = torch.arange(4)
torch.save(x, 'x-file')

In [4]:
x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

In [5]:
y = torch.zeros(4)
torch.save([x, y], 'x-files')
x2, y2 = torch.load('x-files')
x2, y2

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [6]:
mydict = {'x': x, 'y': y}
torch.save(mydict, 'x-dict')
mydict2 = torch.load('x-dict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

## 加载和保存模型参数

In [7]:
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)
    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

In [8]:
net = MLP()
x = torch.randn(2, 20)
y = net(x)

In [9]:
torch.save(net.state_dict(), 'mlp.params')

In [13]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [22]:
y_clone = clone(x)
y_clone == y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

## Exercises

1. 即使不需要将经过训练的模型部署到不同的设备上，存储模型参数还有什么实际的好处?

2. 假设我们只想复用网络的一部分，以将其合并到不同的网络架构中。比如想在一个新的网络中使用之前网络的前两层，该怎么做？

3. 如何同时保存网络架构和参数？需要对架构加上什么限制？