In [76]:
import torch

### Tensor创建
---

In [77]:
torch.arange(12), torch.arange(0,12)

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]))

In [78]:
torch.linspace(0, 1, 12), torch.linspace(0, 12, 7, dtype=torch.int64)

(tensor([0.0000, 0.0909, 0.1818, 0.2727, 0.3636, 0.4545, 0.5455, 0.6364, 0.7273,
         0.8182, 0.9091, 1.0000]),
 tensor([ 0,  2,  4,  6,  8, 10, 12]))

In [79]:
x = torch.tensor([[1,2,3],[2,3,4]])
x.shape, x.size(), x.numel(), x.reshape(-1)

(torch.Size([2, 3]), torch.Size([2, 3]), 6, tensor([1, 2, 3, 2, 3, 4]))

In [80]:
torch.zeros((2,3,4)), torch.ones((2,3,4))

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]))

In [81]:
x = torch.arange(12).reshape(3,4)
torch.zeros_like(x), torch.ones_like(x)

(tensor([[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]),
 tensor([[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]))

In [82]:
torch.randn((3,4)), torch.rand((3,4)), torch.randint(0,12,(3,4))

(tensor([[-0.5507, -1.7433, -0.6381,  0.3876],
         [ 0.9016,  1.1562,  0.4556, -0.3400],
         [ 0.8122,  0.8035, -0.3403, -1.2145]]),
 tensor([[0.1358, 0.4363, 0.2926, 0.1643],
         [0.7649, 0.5035, 0.3782, 0.0620],
         [0.1953, 0.2775, 0.4227, 0.2131]]),
 tensor([[4, 7, 8, 8],
         [6, 8, 0, 1],
         [6, 8, 6, 5]]))

In [83]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## Tensor运算
---

In [84]:
x = torch.tensor([1,2,4,8])
y = torch.ones(4, dtype=torch.int64)*5
x.dtype, y.dtype, x+y, x-y, x*y, x/y, x**y

(torch.int64,
 torch.int64,
 tensor([ 6,  7,  9, 13]),
 tensor([-4, -3, -1,  3]),
 tensor([ 5, 10, 20, 40]),
 tensor([0.2000, 0.4000, 0.8000, 1.6000]),
 tensor([    1,    32,  1024, 32768]))

In [85]:
x = torch.tensor([1,2,3,4])
torch.exp(x), torch.log(x)

(tensor([ 2.7183,  7.3891, 20.0855, 54.5981]),
 tensor([0.0000, 0.6931, 1.0986, 1.3863]))

In [86]:
x = torch.tensor([1,2,3,4]).reshape(-1,2)
y = torch.tensor([5,6,7,8]).reshape(-1,2)
torch.cat((x, y)), torch.cat((x, y), dim=0), torch.cat((x, y), dim=1)

(tensor([[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]),
 tensor([[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]),
 tensor([[1, 2, 5, 6],
         [3, 4, 7, 8]]))

In [87]:
x = torch.tensor([1,2,3,4]).reshape(-1,2)
y = torch.tensor([5,6,3,8]).reshape(-1,2)
z = torch.tensor([1,2,3,8]).reshape(-1,2)

x == y, x == z

(tensor([[False, False],
         [ True, False]]),
 tensor([[ True,  True],
         [ True, False]]))

In [88]:
x = torch.tensor([1,2,3,4]).reshape(-1,2)
x.sum()

tensor(10)

## 广播机制
---
- 规则1：如果两个数组的维度数不同，那么维度较少的数组会在前面补1，直到维度数相同。

- 规则2：如果两个数组的维度大小不同，但其中一个数组的维度为1，那么可以将该数组沿着该维度进行扩展，使其大小与另一个数组的对应维度相同。

- 规则3：如果两个数组的维度大小都不同且都不为1，那么不能进行广播，会引发错误。

- 规则4：如果两个数组在某个维度上的大小相同或其中一个数组的大小为1，在该维度上可以进行广播。

- 规则5：在进行广播时，输出数组的大小是输入数组大小的最大值。

In [89]:
x = torch.arange(3).reshape(3, 1)
y = torch.arange(2).reshape(1, 2)
x, y, x*y

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 0],
         [0, 1],
         [0, 2]]))

In [90]:
x = torch.arange(3).unsqueeze(0).transpose(0, 1)
y = torch.arange(2).unsqueeze(0)
x, y, x*y

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 0],
         [0, 1],
         [0, 2]]))

## 索引与切片
---

In [91]:
x = torch.arange(12).reshape(3,4)
x, x[-1], x[1:3]

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([ 8,  9, 10, 11]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [92]:
x = torch.arange(12).reshape(3, 4)
x[:, 1:3] = 12
x

tensor([[ 0, 12, 12,  3],
        [ 4, 12, 12,  7],
        [ 8, 12, 12, 11]])

## 原地操作
---

In [93]:
x = torch.randn(3)
y = torch.zeros_like(x)
id_x1 = id(x)
x = x + y
id_x2 = id(x)
x[:] = x + y
id_x3 = id(x)
id_x1, id_x2, id_x3

(140063010972176, 140063025210736, 140063025210736)

## Tensor对象转化
---

In [94]:
x = torch.arange(12).reshape(3, 4)
y = x.numpy()
type(x), type(y)

(torch.Tensor, numpy.ndarray)

In [95]:
x = torch.tensor([3.6])
x, x.item(), float(x), int(x)

(tensor([3.6000]), 3.5999999046325684, 3.5999999046325684, 3)

## Exercises
---

1. 运行本节中的代码。将本节中的条件语句X == Y更改为X < Y或X > Y，然后看看你可以得到什么样的张量

In [96]:
x = torch.randn(12).reshape(3,4)
y = torch.randn(12).reshape(3,4)
x < y, x > y

(tensor([[ True,  True,  True, False],
         [False,  True, False, False],
         [ True, False,  True, False]]),
 tensor([[False, False, False,  True],
         [ True, False,  True,  True],
         [False,  True, False,  True]]))

2. 用其他形状（例如三维张量）替换广播机制中按元素操作的两个张量。结果是否与预期相同？

In [97]:
x = torch.arange(24).reshape(2, 2, 6)
y = torch.arange(24).reshape(6, 2, 2, 1)
x+y

tensor([[[[ 0,  1,  2,  3,  4,  5],
          [ 7,  8,  9, 10, 11, 12]],

         [[14, 15, 16, 17, 18, 19],
          [21, 22, 23, 24, 25, 26]]],


        [[[ 4,  5,  6,  7,  8,  9],
          [11, 12, 13, 14, 15, 16]],

         [[18, 19, 20, 21, 22, 23],
          [25, 26, 27, 28, 29, 30]]],


        [[[ 8,  9, 10, 11, 12, 13],
          [15, 16, 17, 18, 19, 20]],

         [[22, 23, 24, 25, 26, 27],
          [29, 30, 31, 32, 33, 34]]],


        [[[12, 13, 14, 15, 16, 17],
          [19, 20, 21, 22, 23, 24]],

         [[26, 27, 28, 29, 30, 31],
          [33, 34, 35, 36, 37, 38]]],


        [[[16, 17, 18, 19, 20, 21],
          [23, 24, 25, 26, 27, 28]],

         [[30, 31, 32, 33, 34, 35],
          [37, 38, 39, 40, 41, 42]]],


        [[[20, 21, 22, 23, 24, 25],
          [27, 28, 29, 30, 31, 32]],

         [[34, 35, 36, 37, 38, 39],
          [41, 42, 43, 44, 45, 46]]]])