In [43]:
import torch

## 标量
---

In [44]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x+y, x*y, x/y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## 向量
---

In [45]:
x = torch.arange(4)
x, x[3], len(x), x.ndim, x.shape, x.size()

(tensor([0, 1, 2, 3]), tensor(3), 4, 1, torch.Size([4]), torch.Size([4]))

## 矩阵
---

In [46]:
x = torch.arange(20).reshape(5,4)
x, x.T

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  4,  8, 12, 16],
         [ 1,  5,  9, 13, 17],
         [ 2,  6, 10, 14, 18],
         [ 3,  7, 11, 15, 19]]))

## 张量
---

In [47]:
x = torch.arange(24).reshape(2,3,4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [48]:
x = torch.randn(2,3)
y = x.clone()
x += torch.ones_like(x)
x, y 

(tensor([[-0.8628,  1.2055,  1.0282],
         [ 0.6488,  1.9246,  1.0194]]),
 tensor([[-1.8628,  0.2055,  0.0282],
         [-0.3512,  0.9246,  0.0194]]))

In [49]:
print(dir(torch.Tensor))

['H', 'T', '__abs__', '__add__', '__and__', '__array__', '__array_priority__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__cuda_array_interface__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__idiv__', '__ifloordiv__', '__ilshift__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__long__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rfloordiv__', '__rls

In [50]:
x = torch.arange(24).reshape(2,3,4)
x, x.sum(axis=[0,1]), x.sum(axis=0), x.sum(axis=0, keepdims=True)

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([60, 66, 72, 78]),
 tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 tensor([[[12, 14, 16, 18],
          [20, 22, 24, 26],
          [28, 30, 32, 34]]]))

In [51]:
x = torch.arange(24, dtype=torch.float32).reshape(2,3,4)
x, x.mean(axis=0)

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]),
 tensor([[ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.],
         [14., 15., 16., 17.]]))

In [52]:
x = torch.arange(24).reshape(2,3,4)
y = x.cumsum(axis=0)   ## 沿某个轴累积求和  
x, y

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 14, 16, 18],
          [20, 22, 24, 26],
          [28, 30, 32, 34]]]))

In [53]:
A = torch.randn(20).reshape(5,4)
x = torch.randn(4)
A, x, torch.mv(A, x)

(tensor([[-0.1390, -0.3164, -2.1334, -1.2904],
         [-0.4456,  1.5825,  0.0880, -1.0508],
         [ 2.0032,  0.7315,  0.8971,  1.1423],
         [-0.2390,  0.7601, -0.0116,  0.7875],
         [ 1.5335, -0.0338,  0.8940,  1.4516]]),
 tensor([-0.8499,  0.3322,  2.4755,  1.8914]),
 tensor([-7.7088, -0.8653,  2.9218,  1.9163,  3.6441]))

In [54]:
A = torch.randn(20).reshape(5,4)
B = torch.randn(12).reshape(4,3)
A, B, torch.mm(A, B) 

(tensor([[ 0.4288,  0.6844, -0.0117,  0.6614],
         [-0.1678, -1.3514, -0.1151, -0.1543],
         [ 0.2425, -1.3238, -0.0081, -0.3247],
         [ 0.3004, -0.0336, -0.5094, -0.3208],
         [-0.3908,  1.5206,  1.8827, -1.9798]]),
 tensor([[ 0.1974, -0.1115, -0.6971],
         [ 0.6615, -0.3760, -0.7031],
         [ 0.2590, -0.2566, -0.4986],
         [ 0.3312, -1.0925,  0.9487]]),
 tensor([[ 0.7533, -1.0247, -0.1468],
         [-1.0080,  0.7250,  0.9782],
         [-0.9375,  0.8275,  0.4577],
         [-0.2011,  0.4603, -0.2361],
         [ 0.7608,  1.1515, -3.6137]]))

In [55]:
torch.norm(torch.tensor([3.0, 4.0]))

tensor(5.)

In [56]:
"""knowhow --- torch.matmul对高维Tensor输入的处理

- 如果两个张量都是一维的,则返回它们的点积（标量）
- 如果两个张量都是二维的,则返回它们的矩阵-矩阵乘积
- 如果第一个参数是一维的,第二个参数是二维的,则在第一个参数的- 维度前面添加一个维度1,以便进行矩阵乘法。在矩阵相乘之后,前置维度会被移除
- 如果第一个参数是二维的,第二个参数是一维的,则返回矩阵向量积
- 如果两个参数至少有一个是N维(其中N > 2),则返回批处理矩阵乘法。在这种情况下,非矩阵维度会被广播
"""

a = torch.Tensor(torch.arange(0,40).reshape((2, 2, 2, 5)))
b = torch.Tensor(torch.arange(0,20).reshape(2, 5, 2))
a, b, a.matmul(b)
a.matmul(b), [[torch.matmul(a[0][0], b[0]), torch.matmul(a[0][1], b[1])],
              [torch.matmul(a[1][0], b[0]), torch.matmul(a[1][1], b[1])]]

(tensor([[[[  60,   70],
           [ 160,  195]],
 
          [[ 860,  920],
           [1210, 1295]]],
 
 
         [[[ 460,  570],
           [ 560,  695]],
 
          [[2260, 2420],
           [2610, 2795]]]]),
 [[tensor([[ 60,  70],
           [160, 195]]),
   tensor([[ 860,  920],
           [1210, 1295]])],
  [tensor([[460, 570],
           [560, 695]]),
   tensor([[2260, 2420],
           [2610, 2795]])]])

## Exercises
---

1. 证明一个矩阵$A$的转置的转置是$A$, 即$(A^T)^T = A$

2. 给出两个矩阵$A$和$B$，证明“它们转置的和”等于“它们和的转置”，即$A^T+B^T = (A+B)^T$

3. 给定任意方阵$A$，$A+A^T$总是对称的吗?为什么?

4. 本节中定义了形状`(2,3,4)`的张量X。`len(X)`的输出结果是什么？

In [57]:
X = torch.randn(24).reshape(2,3,4)
X, len(X)

(tensor([[[-0.3040,  0.0740, -2.7376, -0.8703],
          [-0.4783,  0.6012,  0.6722, -0.8620],
          [ 1.4926, -1.5211,  0.7222,  0.6040]],
 
         [[-0.7243,  0.1576, -0.2154, -0.7686],
          [-0.5517,  1.0391,  0.5049, -0.3055],
          [-0.1807, -0.5764, -0.1027, -0.1325]]]),
 2)

5. 对于任意形状的张量$X$,`len(X)`是否总是对应于$X$特定轴的长度?这个轴是什么?

6. 运行`A/A.sum(axis=1)`，看看会发生什么。请分析一下原因？

In [58]:
A = torch.randn(20).reshape(5,4)
A/A.sum(axis=1) ## 需要keepdim=True,广播机制

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1

7. 考虑一个具有形状`(2,3,4)`的张量，在轴0、1、2上的求和输出是什么形状

In [ ]:
A = torch.randn(24).reshape(2,3,4)
A.sum(axis=0), A.sum(axis=1), A.sum(axis=2), \
    A.sum(axis=0).shape, A.sum(axis=1).shape, A.sum(axis=2).shape